import type { Attraction, LocalStay } from '../types';

export const ATTRACTIONS_BY_CITY: Record<string, Attraction[]> = {
  "dehradun": [
    {
      id: "deb-1",
      name: "Robber's Cave",
      lat: 30.3783,
      lng: 78.0612,
      category: "Adventure",
      description: "A natural river cave formation locally known as Guchhupani. Visitors can wade through cold knee-deep water between narrow conglomerate limestone walls.",
      openingHours: "07:00 AM - 06:00 PM",
      bestTime: "March to June (Summer)",
      nearbyAttractions: ["Malsi Deer Park", "Sahastradhara"],
      visitDuration: "2 hours",
      difficulty: "Moderate",
      photo: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Section_of_Robber_Cave_Dehradun_Uttarakhand_India.jpg"
    },
    {
      id: "deb-2",
      name: "Mindrolling Monastery",
      lat: 30.2599,
      lng: 78.0076,
      category: "Culture",
      description: "One of the largest Buddhist centers in India, featuring a majestic 185-foot-tall Great Stupa and beautiful landscaped gardens.",
      openingHours: "09:00 AM - 07:00 PM",
      bestTime: "October to March",
      nearbyAttractions: ["Clement Town Bazaar"],
      visitDuration: "1.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/5/50/Great_stupa_in_Mindroling.jpg"
    },
    {
      id: "deb-3",
      name: "Forest Research Institute",
      lat: 30.3414,
      lng: 77.9972,
      category: "Museums",
      description: "A premier research institution featuring magnificent Greco-Roman colonial architecture and six museums covering forestry, botany, and timber.",
      openingHours: "09:00 AM - 05:30 PM",
      bestTime: "September to April",
      nearbyAttractions: ["Tapkeshwar Temple"],
      visitDuration: "2.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Forest_research_institute-_dehradun-_uttrakhand-_DSC_001.jpg/960px-Forest_research_institute-_dehradun-_uttrakhand-_DSC_001.jpg"
    },
    {
      id: "deb-4",
      name: "Tapkeshwar Mahadev Temple",
      lat: 30.3552,
      lng: 78.0205,
      category: "Temples",
      description: "A popular cave temple dedicated to Lord Shiva, located on the forest banks of the Tons River, where water droplets naturally drip on the Shivalinga.",
      openingHours: "06:00 AM - 08:00 PM",
      bestTime: "Shivratri Festival",
      nearbyAttractions: ["Forest Research Institute"],
      visitDuration: "1 hour",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Hanuman_Idol_at_Tapkeshwar_Temple..jpg"
    },
    {
      id: "deb-5",
      name: "Maldevta Picnic Spot",
      lat: 30.3496,
      lng: 78.1189,
      category: "Hidden Gems",
      description: "A serene riverside valley surrounded by green hills, popular among locals for weekend picnics and slow riverside walks.",
      openingHours: "24 Hours open",
      bestTime: "October to April",
      nearbyAttractions: ["Sahastradhara"],
      visitDuration: "3 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/1/10/Song_River_Maldevta_Dehradun.jpg"
    },
    {
      id: "deb-6",
      name: "Kumar Sweets & Snacks",
      lat: 30.3222,
      lng: 78.0416,
      category: "Food",
      description: "A legendary local culinary institution famous for its traditional Garhwali sweets, piping hot Samosas, and Rasmalai.",
      openingHours: "08:00 AM - 10:00 PM",
      bestTime: "Evening snack hours",
      nearbyAttractions: ["Paltan Bazaar"],
      visitDuration: "45 mins",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Kachori_MA23.jpg/960px-Kachori_MA23.jpg"
    }
  ],
  "jaipur": [
    {
      id: "jai-1",
      name: "Hawa Mahal",
      lat: 26.9239,
      lng: 75.8267,
      category: "Culture",
      description: "The 'Palace of Winds' is a stunning five-story red and pink sandstone honeycomb facade built in 1799 for royal women to watch street scenes.",
      openingHours: "09:00 AM - 05:00 PM",
      bestTime: "Sunrise photography hours",
      nearbyAttractions: ["City Palace", "Jantar Mantar"],
      visitDuration: "1 hour",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Hawa_Mahal%2C_Jaipur.jpg/960px-Hawa_Mahal%2C_Jaipur.jpg"
    },
    {
      id: "jai-2",
      name: "Galta Ji (Monkey Temple)",
      lat: 26.9168,
      lng: 75.8586,
      category: "Temples",
      description: "An ancient Hindu pilgrimage site with natural water springs and seven sacred bathing pools, nestled between mountain passes and home to friendly macaques.",
      openingHours: "05:00 AM - 07:00 PM",
      bestTime: "Late afternoon / Sunset",
      nearbyAttractions: ["Sisodia Rani Garden"],
      visitDuration: "2 hours",
      difficulty: "Moderate",
      photo: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Zanana_Kund_Aur_Galta_Ji_Ka_Mandir_-_edited.jpg"
    },
    {
      id: "jai-3",
      name: "Panna Meena ka Kund",
      lat: 26.9934,
      lng: 75.8496,
      category: "Hidden Gems",
      description: "A gorgeous symmetrical stepwell and rain-water catchment basin from the 16th century, featuring nested geometric staircases.",
      openingHours: "07:00 AM - 06:00 PM",
      bestTime: "Morning",
      nearbyAttractions: ["Anokhi Museum of Block Printing", "Amber Fort"],
      visitDuration: "45 mins",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/20191219_Panna_Meena_ka_Kund_step_well%2C_Amber%2C_Jaipur%2C_1130_9630.jpg"
    },
    {
      id: "jai-4",
      name: "Nahargarh Fort Cycling Trail",
      lat: 26.9374,
      lng: 75.8156,
      category: "Adventure",
      description: "An energetic cycling loop that winds up the Aravalli hills to Nahargarh Fort, offering panoramic sunrise views of Jaipur city.",
      openingHours: "06:00 AM - 09:00 AM (for cycling)",
      bestTime: "Early morning winter months",
      nearbyAttractions: ["Jaigarh Fort"],
      visitDuration: "3 hours",
      difficulty: "Challenging",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Jaipur%2C_Madhvendra_Palace.jpg/960px-Jaipur%2C_Madhvendra_Palace.jpg"
    },
    {
      id: "jai-5",
      name: "Amer Fort",
      lat: 26.9854,
      lng: 75.8513,
      category: "Culture",
      description: "A majestic hilltop fortress overlooking Maota Lake, famous for its artistic Hindu elements, massive ramparts, and the Sheesh Mahal (mirror palace).",
      openingHours: "09:00 AM - 06:00 PM",
      bestTime: "Late afternoon",
      nearbyAttractions: ["Panna Meena ka Kund", "Jaigarh Fort"],
      visitDuration: "2 hours",
      difficulty: "Moderate",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/20191219_Fort_Amber%2C_Amer%2C_Jaipur_0955_9481.jpg/960px-20191219_Fort_Amber%2C_Amer%2C_Jaipur_0955_9481.jpg"
    },
    {
      id: "jai-6",
      name: "Albert Hall Museum",
      lat: 26.9116,
      lng: 75.8193,
      category: "Museums",
      description: "The oldest state museum in Rajasthan, showcasing a rich collection of artifacts, local paintings, carpets, and an Egyptian mummy.",
      openingHours: "09:00 AM - 05:00 PM, 07:00 PM - 10:00 PM",
      bestTime: "Night viewing hours",
      nearbyAttractions: ["Jaipur Zoo"],
      visitDuration: "1.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Albert_Hall_Museum_Jaipur.jpg/800px-Albert_Hall_Museum_Jaipur.jpg"
    }
  ],
  "varanasi": [
    {
      id: "var-1",
      name: "Dashashwamedh Ghat",
      lat: 25.3072,
      lng: 83.0101,
      category: "Culture",
      description: "The spiritual center of Varanasi, famous for its daily evening Ganga Aarti ceremony where priests perform rhythmic rituals of light and fire.",
      openingHours: "Open 24 Hours (Aarti at 06:30 PM)",
      bestTime: "Sunset / Evening Aarti hours",
      nearbyAttractions: ["Kashi Vishwanath Temple", "Manikarnika Ghat"],
      visitDuration: "1.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Aarti%2C_Ganga_Aarti_at_Dashashwamedh_Ghat%2C_Varanasi.jpg/800px-Aarti%2C_Ganga_Aarti_at_Dashashwamedh_Ghat%2C_Varanasi.jpg"
    },
    {
      id: "var-2",
      name: "Kashi Vishwanath Temple",
      lat: 25.3109,
      lng: 83.0102,
      category: "Temples",
      description: "One of the most famous Hindu temples, dedicated to Lord Shiva (Vishwanatha) and standing on the western bank of the holy Ganges.",
      openingHours: "04:00 AM - 11:00 PM",
      bestTime: "Early morning",
      nearbyAttractions: ["Dashashwamedh Ghat"],
      visitDuration: "1 hour",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Kashi_Vishwanath_Temple.jpg/800px-Kashi_Vishwanath_Temple.jpg"
    },
    {
      id: "var-3",
      name: "Sarnath Buddhist Site",
      lat: 25.3762,
      lng: 83.0223,
      category: "Culture",
      description: "The historical park where Gautama Buddha first taught the Dharma after attaining enlightenment, featuring the ancient Dhamek Stupa.",
      openingHours: "06:00 AM - 06:00 PM",
      bestTime: "October to March",
      nearbyAttractions: ["Sarnath Archaeological Museum"],
      visitDuration: "2 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Dhamek_Stupa.jpg/800px-Dhamek_Stupa.jpg"
    },
    {
      id: "var-4",
      name: "Kachori Gali",
      lat: 25.3115,
      lng: 83.0118,
      category: "Food",
      description: "A narrow alleyway in old Varanasi famous for street stalls serving legendary kachori-sabzi and steaming hot jalebi since generations.",
      openingHours: "07:00 AM - 01:00 PM",
      bestTime: "Morning Breakfast hours",
      nearbyAttractions: ["Vishwanath Gali"],
      visitDuration: "45 mins",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Kachori_MA23.jpg/960px-Kachori_MA23.jpg"
    },
    {
      id: "var-5",
      name: "Ramnagar Fort",
      lat: 25.2679,
      lng: 83.0272,
      category: "Hidden Gems",
      description: "A majestic 18th-century sandstone fortress on the eastern bank of the Ganges, featuring a vintage museum of royal cars and weapons.",
      openingHours: "10:00 AM - 05:00 PM",
      bestTime: "November to February",
      nearbyAttractions: ["Vyas Temple"],
      visitDuration: "1.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Ramnagar_Fort_Varanasi.jpg/800px-Ramnagar_Fort_Varanasi.jpg"
    },
    {
      id: "var-6",
      name: "Lakhaniya Dari Waterfall",
      lat: 24.9687,
      lng: 83.0763,
      category: "Adventure",
      description: "A hidden waterfall and forest trekking trail located in the Vindhyan hills outside the city, popular for adventure picnics.",
      openingHours: "06:00 AM - 05:00 PM",
      bestTime: "Monsoon Season (July to September)",
      nearbyAttractions: ["Chunar Fort"],
      visitDuration: "3 hours",
      difficulty: "Moderate",
      photo: "https://images.unsplash.com/photo-1509909756405-be0199881695?auto=format&fit=crop&w=600&q=80"
    }
  ],
  "goa": [
    {
      id: "goa-1",
      name: "Basilica of Bom Jesus",
      lat: 15.5009,
      lng: 73.9116,
      category: "Culture",
      description: "A UNESCO World Heritage site holding the mortal remains of St. Francis Xavier, featuring gorgeous Baroque Architecture.",
      openingHours: "09:00 AM - 06:30 PM",
      bestTime: "October to March",
      nearbyAttractions: ["Se Cathedral", "Archaeological Museum"],
      visitDuration: "1 hour",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Basilica_of_Bom_Jesus.jpg/800px-Basilica_of_Bom_Jesus.jpg"
    },
    {
      id: "goa-2",
      name: "Dudhsagar Waterfalls",
      lat: 15.3179,
      lng: 74.3149,
      category: "Adventure",
      description: "A majestic four-tiered waterfall on the Mandovi River, looking like a cascading sea of milk amidst deep jungle trails.",
      openingHours: "09:00 AM - 05:00 PM",
      bestTime: "Post-monsoon (October to December)",
      nearbyAttractions: ["Bhagwan Mahavir Sanctuary"],
      visitDuration: "4 hours",
      difficulty: "Challenging",
      photo: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Dudhsagar_falls_Entry_gate_Goa.jpg"
    },
    {
      id: "goa-3",
      name: "Fontainhas Latin Quarter",
      lat: 15.4989,
      lng: 73.6429,
      category: "Hidden Gems",
      description: "An old Latin quarter in Panaji, featuring brightly colored Portuguese-style houses, cozy bakeries, and narrow streets.",
      openingHours: "Open 24 Hours",
      bestTime: "Late morning or early evening",
      nearbyAttractions: ["Panaji Church", "Mandovi River Cruise"],
      visitDuration: "1.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/d/db/Road_along_Vasco-da-gama_residence_in_Fontainhas%2C_Panaji.jpg"
    },
    {
      id: "goa-4",
      name: "Anjuna Flea Market",
      lat: 15.5794,
      lng: 73.7432,
      category: "Culture",
      description: "A vibrant weekly beachfront market offering local spices, hippie handicrafts, live musical bands, and local beach snacks.",
      openingHours: "09:00 AM - 06:00 PM (Wednesdays only)",
      bestTime: "Wednesday afternoon",
      nearbyAttractions: ["Anjuna Beach"],
      visitDuration: "2 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/d/db/Anjuna_beach_Goa.jpg"
    },
    {
      id: "goa-5",
      name: "Mangeshi Temple",
      lat: 15.4439,
      lng: 73.9687,
      category: "Temples",
      description: "A prominent 450-year-old temple dedicated to Lord Shiva, featuring a beautiful deepastambha (seven-story lamp tower).",
      openingHours: "06:00 AM - 08:00 PM",
      bestTime: "Early morning",
      nearbyAttractions: ["Shantadurga Temple"],
      visitDuration: "1 hour",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Mangeshi_temple.jpg/800px-Mangeshi_temple.jpg"
    },
    {
      id: "goa-6",
      name: "Fisherman's Wharf",
      lat: 15.2678,
      lng: 73.9429,
      category: "Food",
      description: "A celebrated riverside culinary spot serving traditional Goan fish curry, recheado masala, and fresh river catches.",
      openingHours: "12:00 PM - 11:00 PM",
      bestTime: "Lunch or Dinner hours",
      nearbyAttractions: ["Cavelossim Beach"],
      visitDuration: "1.5 hours",
      difficulty: "Easy",
      photo: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Goan_typical_meal_--_fish%2C_curry_and_rice.jpg"
    }
  ]
};

export const LOCAL_STAYS_BY_CITY: Record<string, LocalStay[]> = {
  "dehradun": [
    {
      id: "stay-deb-1",
      name: "Dwarika Homestay & Orchard",
      type: "Apple Orchard",
      location: "Rajpur Foothills, Dehradun",
      price: "₹3,200 / night",
      rating: 4.9,
      photos: ["https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=500&q=80"],
      cultureExperience: ["Fresh Apple Harvesting", "Garhwali Cooking Class", "Stargazing Bonfire"],
      hostName: "Mama Dwarika Negi",
      description: "Nestled in the higher foothills of Rajpur, this traditional stone homestay is surrounded by organic apple trees and wild berries."
    },
    {
      id: "stay-deb-2",
      name: "The Doon Valley Tea Estate Retreat",
      type: "Tea Estate",
      location: "Vikasnagar, Dehradun Outskirts",
      price: "₹4,500 / night",
      rating: 4.8,
      photos: ["https://upload.wikimedia.org/wikipedia/commons/e/e0/Tea_garden_at_Nagri_in_the_Kangra_Valley_of_Himachal_Pradesh%2C_India.jpg"],
      cultureExperience: ["Tea Leaf Plucking", "Artisan Woodcarving Workshop", "Local Village Walk"],
      hostName: "Ranjit & Devika Singh",
      description: "Stay in a restored 1920s colonial planter bungalow. Wake up to the aroma of fresh tea leaves and misty morning walks."
    }
  ],
  "jaipur": [
    {
      id: "stay-jai-1",
      name: "Haveli Kalwara Heritage Homestay",
      type: "Homestay",
      location: "Johari Bazaar, Old City Jaipur",
      price: "₹2,800 / night",
      rating: 4.7,
      photos: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=500&q=80"],
      cultureExperience: ["Block Printing Tutorial", "Rajasthani Puppetry Show", "Traditional Dal-Baati Dinner"],
      hostName: "Thakur Mahendra Singh",
      description: "A beautifully preserved 17th-century Haveli within the walls of the Pink City, run by direct descendants of royal court officers."
    }
  ],
  "varanasi": [
    {
      id: "stay-var-1",
      name: "Ganga View Heritage Kothi",
      type: "Homestay",
      location: "Dashashwamedh Ghat, Old Varanasi",
      price: "₹3,800 / night",
      rating: 4.9,
      photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=500&q=80"],
      cultureExperience: ["Morning Raga Concert", "Ghat Walk with Local Guide", "Aarti Boat Tour"],
      hostName: "Pandit Shivnath Shastri",
      description: "A grand 150-year-old riverfront villa facing the Ganges river ghats, offering private balconies to view sunrise rituals."
    },
    {
      id: "stay-var-2",
      name: "Kashi Clay Pottery Homestay",
      type: "Village Stay",
      location: "Sarnath Craft Village, Varanasi",
      price: "₹2,100 / night",
      rating: 4.7,
      photos: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=500&q=80"],
      cultureExperience: ["Clay Pot Throwing", "Banarasi Silk Weaving Visit", "Sattvik Dinner"],
      hostName: "Sohan & Reema Prajapati",
      description: "Stay with local clay artisans. Learn traditional pot throwing and enjoy authentic home-cooked Banarasi meals."
    }
  ],
  "goa": [
    {
      id: "stay-goa-1",
      name: "Casa de Saffron Portuguese Villa",
      type: "Farm Stay",
      location: "Aldona Village, North Goa",
      price: "₹4,200 / night",
      rating: 4.8,
      photos: ["https://upload.wikimedia.org/wikipedia/commons/f/f3/Spice_Plantation_in_Goa.JPG"],
      cultureExperience: ["Feni Distilling Tutorial", "Spices Plantation Tour", "Baking Goan Bebinca"],
      hostName: "Maria & Senor D'Souza",
      description: "An authentic 1850 Portuguese estate surrounded by mango trees and pepper vines, offering deep glimpses into old Konkan life."
    },
    {
      id: "stay-goa-2",
      name: "Konkan Palms Beach Shack Retreat",
      type: "Village Stay",
      location: "Patnem Beach, South Goa",
      price: "₹3,000 / night",
      rating: 4.6,
      photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80"],
      cultureExperience: ["Traditional Fishing Net Cast", "Coconut Husk Crafting", "Konkan Seafood BBQ"],
      hostName: "Joao Fernandes",
      description: "Charming eco-cottages tucked under coconut groves along South Goa's quiet sandy beaches, run by a traditional local fisherman family."
    }
  ]
};
